name: github_search_common
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: phillywiggins <email@example.com>

environment:
  sdk: '>=2.0.0-dev.69.5 <3.0.0'

dependencies:
  path: ^1.4.1
  meta: ^1.1.0
  meta_types_json: ^0.0.1
  meta_types: ^0.1.0
  http: 0.11.3+17
  rxdart: ^0.18.1

dev_dependencies:
  test: ^1.0.0
  mockito: ^3.0.0
  build_runner: ^0.9.0
  meta_types_generator: ^0.1.0
  meta_types_json_generator: ^0.0.1
